name: petopt
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16
  google_sign_in: ^5.3.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  freezed_annotation: ^2.0.3
  flutter_hooks: ^0.18.4
  equatable: ^2.0.3
  go_router: ^3.1.0
  ionicons: ^0.1.2
  formz: ^0.4.1
  flutter_adaptive_ui:
    path: E:/pr/flutter_flexible_ui/packages/flutter_adaptive_ui

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
