// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqPhvMK2IoB15FRWJR6YG4IsvVsYb0Jhc',
    appId: '1:103614387031:android:21c0401a90db16fd492412',
    messagingSenderId: '103614387031',
    projectId: 'petopt-d7709',
    databaseURL: 'https://petopt-d7709-default-rtdb.firebaseio.com',
    storageBucket: 'petopt-d7709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIWiIayvFzLoPWku_aFV_-p4rj_tMts0U',
    appId: '1:103614387031:ios:2ccdc62a7933157e492412',
    messagingSenderId: '103614387031',
    projectId: 'petopt-d7709',
    databaseURL: 'https://petopt-d7709-default-rtdb.firebaseio.com',
    storageBucket: 'petopt-d7709.appspot.com',
    androidClientId: '103614387031-ecqioebobnaiulgv763hvq8o8ai248o8.apps.googleusercontent.com',
    iosClientId: '103614387031-e6aq2ho8bmcakplp60khcf956r1ep68j.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
